name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type checking
      run: npm run check --if-present || echo "No check script found, skipping type checking"
    
    - name: Build application
      run: npm run build
      
    - name: Run tests (if available)
      run: npm test --if-present

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Display Dockerfile content
      run: cat Dockerfile
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: mediahub:latest
        build-args: |
          VITE_STRIPE_PUBLIC_KEY=pk_test_example
          VITE_API_BASE_URL=
        cache-from: type=gha
        cache-to: type=gha,mode=max

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: npm audit --audit-level=moderate

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for common issues
      run: |
        echo "Checking for common issues..."
        # Check for console.log statements
        if grep -r "console\.log" client/src/ server/ shared/ --exclude-dir=node_modules || true; then
          echo "Warning: Found console.log statements. Consider using proper logging."
        fi
        # Check for TODO comments
        if grep -r "TODO\|FIXME" . --exclude-dir=node_modules --exclude-dir=.git || true; then
          echo "Info: Found TODO/FIXME comments."
        fi